name: Composite Action Deploy
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache Dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'true'
      - name: Output Cache Information
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Run Linting
        run: npm run lint --prefix second-action
      - name: Run tests
        run: npm run test --prefix second-action
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
      - name: Build Project
        run: npm run build --prefix second-action
      - name: Publish JS filename
        id: publish
        run: find second-action/dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            second-action/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying the project..."