name: Use Reuseable Deploy
on: workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
            name: dist-files
            path: second-action/dist
  deploy:
    uses: ./.github/workflows/reuseable.yml
    with:
      artifact-name: dist-files
  print-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy
        run: echo "${{ needs.deploy.outputs.result }}"